NMCT/Controllers/ContactFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NMCT.Models;
using NMCT.CustomAttribute;
using NMCT.Models.ViewModels;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using System.Net;

namespace NMCT.Controllers
{
    public class ContactFormController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [HttpGet]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager,Moderator")]
        public ActionResult Index(int? status, string search = null)
        {
            var contactForms = db.ContactForms.ToList();

            ViewBag.Employees = GetEmployees();

            return View(contactForms);
        }

        [NonAction]
        public List<SelectListItem> GetEmployees()
        {
            var managers = db.Database.SqlQuery<UserByRoleViewModel>("dbo.GetUsersByRole 'Manager'").ToList();
            var moderators = db.Database.SqlQuery<UserByRoleViewModel>("dbo.GetUsersByRole 'Moderator'").ToList();

            var employees = new List<SelectListItem>();

            employees.Add(new SelectListItem() { Text = "Choose user to assign...", Value = "" });

            managers.ForEach(m => employees.Add(new SelectListItem() { Text = m.UserName, Value = m.UserName }));
            moderators.ForEach(m => employees.Add(new SelectListItem() { Text = m.UserName, Value = m.UserName }));

            return employees;
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(FormCollection collection)
        {
            bool success = false;
            var userid = User.Identity.GetUserId();
            string userName = db.Users.Find(userid).UserName;

            ContactForm form = new ContactForm();

            form.SubmissionDate = DateTime.Now;
            form.UserName = userName;
            form.FormStatus = FormStatus.Submitted;
            form.Title = collection["Title"];
            form.Content = collection["Content"];
            FormCategory cat;
            success = Enum.TryParse(collection["FormCategory"], out cat);
            if (success)
            {
                form.FormCategory = cat;

                db.ContactForms.Add(form);
                db.SaveChanges();

                return RedirectToAction("Submitted");
            }

            ViewBag.Message = "Something went wrong.";
            return View(form);
        }

        [HttpGet]
        public ActionResult Submitted()
        {
            return View();
        }

        [HttpGet]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager,Moderator")]
        public ActionResult ManageContactForm(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            ContactForm form = db.ContactForms.Find(id);

            if (form == null)
                return HttpNotFound();

            ViewBag.Employees = GetEmployees();

            return View(form);
        }

        [HttpPost]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager,Moderator")]
        public async Task<JsonResult> AssignUser(string userName, int formID)
        {
            if (userName == null)
                return Json("User Name not supplied. Please contact an administrator if this issue keeps occurring.");

            ContactForm form = db.ContactForms.FirstOrDefault(f => f.FormID == formID);

            if (form == null)
                return Json("Couldn't find form.  Please contact an administrator if this issue keeps occurring.");

            if (form.FormStatus == FormStatus.Submitted && userName != "")
                form.FormStatus = FormStatus.Assigned;
            else if (form.FormStatus == FormStatus.Assigned & userName == "")
                form.FormStatus = FormStatus.Submitted;                

            form.AssignedUserName = userName;
            db.SaveChanges();

            if (userName == "")
                return Json("This form has been unassigned.");

            return Json("This form has been assigned to " + userName + ".");
        }

        [HttpPost]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager,Moderator")]
        public async Task<JsonResult> SetStatus(int status, int formID)
        {
            ContactForm form = db.ContactForms.FirstOrDefault(f => f.FormID == formID);

            if (form == null)
                return Json("Couldn't find form. Please contact an administrator if this issue keeps occurring.");

            if ((FormStatus)status == FormStatus.Resolved)
                form.ResolvedDate = DateTime.Now;
            else
                form.ResolvedDate = null;

            form.FormStatus = (FormStatus)status;
            db.SaveChanges();

            return Json("This form has been changed to a " + form.FormStatus.ToString() + " status");
        }
    }
}

NMCT/Controllers/IdentityRoleController.cs
using Microsoft.AspNet.Identity.EntityFramework;
using NMCT.CustomAttribute;
using NMCT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace NMCT.Controllers
{
    public class IdentityRoleController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: IdentityRole
        [HttpGet]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator")]
        public ActionResult Index()
        {
            return View(db.Roles.ToList());
        }
                
        [HttpGet]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator")]
        public ActionResult Details(string id = null)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            else
            {
                IdentityRole role = db.Roles.Find(id);
                if (role == null)
                    return HttpNotFound();
                else
                {
                    ViewBag.RoleName = role.Name;
                    return View(role);
                }                    
            }
        }

        [HttpGet]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator")]
        public ActionResult Create([Bind(Include = "Id, Name")] IdentityRole role)
        {
            if (ModelState.IsValid)
            {
                db.Roles.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(role);
        }

        [HttpGet]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator")]
        public ActionResult Edit(string id = null)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            IdentityRole role = db.Roles.Find(id);

            if (role == null)
                return HttpNotFound();

            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator")]
        public ActionResult Edit([Bind(Include = "Id, Name")] IdentityRole role)
        {
            if (ModelState.IsValid)
            {
                db.Entry(role).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(role);
        }

        [HttpGet]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator")]
        public ActionResult Delete(string id = null)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            IdentityRole role = db.Roles.Find(id);

            if (role == null)
                return HttpNotFound();

            return View(role);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator")]
        public ActionResult DeleteConfirmed(string id = null)
        {
            IdentityRole identityRoleTemp = db.Roles.Find(id);
            db.Roles.Remove(identityRoleTemp);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

NMCT/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NMCT.Models;
using NMCT.CustomAttribute;
using NMCT.Models.ViewModels;
using System.Threading.Tasks;

namespace NMCT.Controllers
{
    public class ReviewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Reviews
        [HttpGet]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager,Moderator")]
        public ActionResult Index(string sortby, string search, int trailid = 0)
        {
            var trails = db.Trail.ToList();

            ViewBag.TrailList = trails;
            ViewBag.TrailID = trailid;

            //filtering
            IEnumerable<Review> reviews = db.Review.ToList();

            if (trailid > 0)
                reviews = reviews.Where(r => r.TrailID == trailid);

            if (!String.IsNullOrWhiteSpace(search))
                reviews = reviews.Where(r => r.UserName.ToUpper().Contains(search.ToUpper()));

            //sorting setup
            ViewBag.DateSort = sortby == "Date" ? "Date_desc" : "Date";
            ViewBag.RatingSort = sortby == "Rating" ? "Rating_desc" : "Rating";
            ViewBag.SortBy = sortby;

            //sorting
            switch (sortby)
            {
                case "Date":
                    reviews = reviews.OrderBy(r => r.DateCreated);
                    ViewBag.DateSortArrow = "glyphicon-chevron-up";
                    ViewBag.RatingSortArrow = null;
                    break;

                case "Date_desc":
                    reviews = reviews.OrderByDescending(r => r.DateCreated);
                    ViewBag.DateSortArrow = "glyphicon-chevron-down";
                    ViewBag.RatingSortArrow = null;
                    break;

                case "Rating":
                    reviews = reviews.OrderBy(r => r.Rating);
                    ViewBag.RatingSortArrow = "glyphicon-chevron-up";
                    ViewBag.DateSortArrow = null;
                    break;

                case "Rating_desc":
                    reviews = reviews.OrderByDescending(r => r.Rating);
                    ViewBag.RatingSortArrow = "glyphicon-chevron-down";
                    ViewBag.DateSortArrow = null;
                    break;

                default:
                    reviews = reviews.OrderByDescending(r => r.DateCreated);
                    ViewBag.NameSortArrow = null;
                    ViewBag.CountySortArrow = null;
                    break;
            }

            return View(reviews);
        }

        // GET: Reviews/Details/5
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager,Moderator")]
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Review.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }
        
        // GET: Reviews/Edit/5
        [HttpGet]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager,Moderator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Review.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager,Moderator")]
        public ActionResult Edit([Bind(Include = "ReviewID,Title,Content,UserName")] Review review)
        {
            if (ModelState.IsValid)
            {
                var excluded = new[] { "DateCreated", "TrailID", "Rating" };
                db.Entry(review).State = EntityState.Modified;
                foreach (var name in excluded)
                {
                    db.Entry(review).Property(name).IsModified = false;
                }                
                db.SaveChanges();
                return RedirectToAction("Index", new { id = review.TrailID });
            }
            return View(review);
        }

        // GET: Reviews/Delete/5
        [HttpGet]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Review.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager")]
        public ActionResult DeleteConfirmed(int id)
        {
            Review review = db.Review.Find(id);
            db.Review.Remove(review);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = review.TrailID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NMCT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Northern Michigan Cycling Trails</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Northern Michigan Cycling Trails", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Trails", "Index", "Trails")</li>
                    <li>@Html.ActionLink("Events", "Index", "Events")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>                    
                    @if (User.IsInRole("Administrator"))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                User Admin
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("User Management", "Index", "Account")</li>
                                <li>@Html.ActionLink("Roles Management", "Index", "IdentityRole")</li>
                            </ul>
                        </li>
                    }
                    @if (User.IsInRole("Administrator") || User.IsInRole("Manager"))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Site Admin
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Manage Trails", "Index", "Trails")</li>
                                <li>@Html.ActionLink("Manage Reviews", "Index", "Reviews")</li>
                                <li>@Html.ActionLink("Manage Events", "Index", "Events")</li>
                                <li>@Html.ActionLink("Manage Feedback", "Index", "ContactForm")</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Northern Michigan Cycling Trails</p>
        </footer>
    </div>

    <script>
        $(document).ready(function () {
            $('#createReview').popup({
                transition: 'all 0.2s', opacity: 0.75
            });
            $('.datepicker').datepicker({
                showOtherMonths: true,
                selectOtherMonths: true
            });
        });
    </script>
</body>

</html>