NMCT/Models/Trail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace NMCT.Models
{
    public class Trail
    {
        [Key]
        public int TrailID { get; set; }
        [Required]
        [Display(Name="Trail Name")]
        public string Name { get; set; }
        public string County { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
    }
}

NMCT/Controllers/TrailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NMCT.Models;
using NMCT.CustomAttribute;
using NMCT.Models.ViewModels;
using System.Threading.Tasks;

namespace NMCT.Controllers
{
    public class TrailsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Trails
        public ActionResult Index(string sortby, string county, string search)
        {
            IEnumerable<Trail> trails = db.Trail.ToList();

            ViewBag.Counties = trails.Select(t => t.County).Distinct().OrderBy(x => x);

            //filtering
            if (!String.IsNullOrWhiteSpace(search))
            {
                trails = trails.Where(t => t.Name.ToUpper().Contains(search.ToUpper()));
                ViewBag.SearchFilter = search;
            }

            if (!String.IsNullOrWhiteSpace(county))
            {
                trails = trails.Where(t => t.County == county);
                ViewBag.CountyFilter = county;
            }

            //sorting setup
            ViewBag.NameSort = sortby == "Name" ? "Name_desc" : "Name";
            ViewBag.CountySort = sortby == "County" ? "County_desc" : "County";
            ViewBag.SortBy = sortby;

            //sorting
            switch (sortby)
            {
                case "Name":
                    trails = trails.OrderBy(t => t.Name);
                    ViewBag.NameSortArrow = "glyphicon-chevron-up";
                    ViewBag.CountySortArrow = null;
                    break;

                case "Name_desc":
                    trails = trails.OrderByDescending(t => t.Name);
                    ViewBag.NameSortArrow = "glyphicon-chevron-down";
                    ViewBag.CountySortArrow = null;
                    break;

                case "County":
                    trails = trails.OrderBy(t => t.County);
                    ViewBag.CountySortArrow = "glyphicon-chevron-up";
                    ViewBag.NameSortArrow = null;
                    break;

                case "County_desc":
                    trails = trails.OrderByDescending(t => t.County);
                    ViewBag.CountySortArrow = "glyphicon-chevron-down";
                    ViewBag.NameSortArrow = null;
                    break;

                default:
                    trails = trails.OrderBy(t => t.TrailID);
                    ViewBag.NameSortArrow = null;
                    ViewBag.CountySortArrow = null;
                    break;
            }

            return View(trails);
        }

        // GET: Trails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trail trail = db.Trail.Find(id);
            if (trail == null)
            {
                return HttpNotFound();
            }

            //get total stats for trail reviews
            TrailReviewStatsViewModel stats = new TrailReviewStatsViewModel(id);
            var reviews = db.Review.Where(t => t.TrailID == id).ToList();

            stats.Rating1 = reviews.Where(t => t.Rating == 1).Count();
            stats.Rating2 = reviews.Where(t => t.Rating == 2).Count();
            stats.Rating3 = reviews.Where(t => t.Rating == 3).Count();
            stats.Rating4 = reviews.Where(t => t.Rating == 4).Count();
            stats.Rating5 = reviews.Where(t => t.Rating == 5).Count();

            stats.Rating = ((stats.Rating1) + (stats.Rating2 * 2) + (stats.Rating3 * 3) + (stats.Rating4 * 4) + (stats.Rating5 * 5)) / (reviews.Count() == 0 ? 1.00 : (double)reviews.Count());
            stats.Rating = Math.Round(stats.Rating, 2);

            ViewBag.Stats = stats;
            ViewBag.TrailID = trail.TrailID;

            return View(trail);
        }

        public ActionResult ListOfReviewsByTrail(int id, int? rating)
        {
            var trailReviews = new List<Review>();

            if (rating != null && rating >= 1 && rating <= 5)
                trailReviews = db.Review.Where(a => a.TrailID == id).Where(a => a.Rating == rating).ToList();
            else
                trailReviews = db.Review.Where(a => a.TrailID == id).ToList();

            trailReviews.OrderByDescending(a => a.DateCreated);

            return PartialView(trailReviews);
        }

        // GET: Trails/Create
        [HttpGet]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Trails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Admin,Manager")]
        public ActionResult Create([Bind(Include = "TrailID,Name,County,Longitude,Latitude,Description,URL")] Trail trail)
        {
            if (ModelState.IsValid)
            {
                db.Trail.Add(trail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(trail);
        }

        // GET: Trails/Edit/5
        [HttpGet]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trail trail = db.Trail.Find(id);
            if (trail == null)
            {
                return HttpNotFound();
            }
            return View(trail);
        }

        // POST: Trails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager")]
        public ActionResult Edit([Bind(Include = "TrailID,Name,County,Longitude,Latitude,Description,URL")] Trail trail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trail);
        }

        // GET: Trails/Delete/5
        [HttpGet]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trail trail = db.Trail.Find(id);
            if (trail == null)
            {
                return HttpNotFound();
            }
            return View(trail);
        }

        // POST: Trails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeOrRedirectAttribute(Roles = "Administrator,Manager")]
        public ActionResult DeleteConfirmed(int id)
        {
            Trail trail = db.Trail.Find(id);
            db.Trail.Remove(trail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("UserCreateReview")]
        [AuthorizeOrRedirectAttribute]
        public async Task<JsonResult> UserCreateReview(FormCollection collection)
        {
            var review = new Review();
            var user = User.Identity;
            string mess = "";

            int rating;
            int trailid;
            bool valid = true;

            //validate information
            if (!int.TryParse(collection["Rating"], out rating))
            {
                valid = false;
            }
            if (!int.TryParse(collection["TrailID"], out trailid))
            {
                valid = false;
            }

            if (!valid)
                return Json(new { status = "Error", message = "Review is invalid."});

            review.UserName = user.Name;
            review.DateCreated = DateTime.Now;
            review.Rating = rating;
            review.Title = collection["Title"];
            review.TrailID = trailid;
            review.Content = collection["Content"];

            if (ModelState.IsValid)
            {
                db.Review.Add(review);
                db.SaveChanges();
                return Json(new { status = "Success", message = "Success" });
            }

            return Json(new { status = "Error", message = "ModelState Not Valid" });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NMCT/Views/Trails/Create.cshtml
@model NMCT.Models.Trail

@{
    ViewBag.Title = "Create Trail";
}

<h2>Trail Management | Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Trail Information</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.County, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.County, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.County, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = 5})
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Trails", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NMCT/Views/Trails/Delete.cshtml
@model NMCT.Models.Trail

@{
    ViewBag.Title = "Delete Trail";
}

<h2>Trail Management | Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trail Information</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.County)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.County)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Trails", "Index")
        </div>
    }
</div>

NMCT/Views/Trails/Details.cshtml
@model NMCT.Models.Trail

@{
    ViewBag.Title = "Trail Details";
    NMCT.Models.ViewModels.TrailReviewStatsViewModel stats = ViewBag.stats;
}

<h2>Trail Details</h2>

<div class="col-md-6">
    <h4>Details For: @Model.Name</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.County)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.County)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            <a href="@Model.URL" target="_blank">@Html.DisplayFor(model => model.URL)</a>
        </dd>

    </dl>

    @if (User.IsInRole("Administrator") || User.IsInRole("Manager"))
    {
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.TrailID }) | @Html.ActionLink("Back to Trails", "Index")
        </p>
    }
    else
    {
        <p>
            @Html.ActionLink("Back to Trails", "Index")
        </p>
    }
</div>

<div class="col-md-6" id="map_canvas" style="height:400px"></div>

<div class="clearfix"></div>

<div class="col-md-12">
    <hr />
    <div>
        <a href="#" type="button" class="createReview_open ">Add a Review</a>
    </div>

    <div class="col-md-3" id="reviewStats">
        <h3>Reviews</h3>
        <div class="list-group">
            <a class="list-group-item reviewFilter active text-right" data-value="0">Average Rating: @stats.Rating<i class='fa fa-star fa-fw'></i></a>
            <a class="list-group-item reviewFilter" data-value="5"><span class="badge"> @stats.Rating5 </span><i class='fa fa-star fa-fw'></i><i class='fa fa-star fa-fw'></i><i class='fa fa-star fa-fw'></i><i class='fa fa-star fa-fw'></i><i class='fa fa-star fa-fw'></i></a>
            <a class="list-group-item reviewFilter" data-value="4"><span class="badge"> @stats.Rating4 </span><i class='fa fa-star fa-fw'></i><i class='fa fa-star fa-fw'></i><i class='fa fa-star fa-fw'></i><i class='fa fa-star fa-fw'></i></a>
            <a class="list-group-item reviewFilter" data-value="3"><span class="badge"> @stats.Rating3 </span><i class='fa fa-star fa-fw'></i><i class='fa fa-star fa-fw'></i><i class='fa fa-star fa-fw'></i></a>
            <a class="list-group-item reviewFilter" data-value="2"><span class="badge"> @stats.Rating2 </span><i class='fa fa-star fa-fw'></i><i class='fa fa-star fa-fw'></i></a>
            <a class="list-group-item reviewFilter" data-value="1"><span class="badge"> @stats.Rating1 </span><i class='fa fa-star fa-fw'></i></a>
        </div>        
    </div>

    <div class="col-md-5"  style="overflow-y:auto;max-height:320px;" id="reviewList">
        @if (@stats.Rating > 0)
        {
            {Html.RenderAction("ListOfReviewsByTrail", new { id = ViewBag.TrailID, rating = 0 });}
        }
        else
        {
            <p class="text-info"><strong>No reviews yet. Be the first to review @Model.Name!</strong></p>
        }

    </div>

    <div class="col-md-4" id="reviewInfo">
        @if (@stats.Rating > 0)
        {
            <h4 id="selectedReviewTitle"></h4>
            <hr />
            <p id="selectedReviewContent"></p>
            <p>
                <span id="selectedReviewUser"></span>
                <br />
                <span id="selectedReviewDate"></span>
            </p>
        }
    </div>
</div>

<div class="clearfix"></div>

<div id="createReview" class="popover">
    <div class="popover-title">
        <h4>Review @Model.Name</h4>
    </div>
    @using (Html.BeginForm("", "", FormMethod.Post, htmlAttributes: new { @class="form form-horizontal reviewForm"})){
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()

        @Html.Hidden("TrailID")
        @Html.Hidden("Rating")
        
        if (User.Identity.IsAuthenticated)
        {
        <div class='rating-stars text-center popover-content'>
            <ul id='stars'>
                <li class='star' title='Poor' data-value='1'><i class='fa fa-star fa-fw'></i></li>
                <li class='star' title='Fair' data-value='2'><i class='fa fa-star fa-fw'></i></li>
                <li class='star' title='Good' data-value='3'><i class='fa fa-star fa-fw'></i></li>
                <li class='star' title='Excellent' data-value='4'><i class='fa fa-star fa-fw'></i></li>
                <li class='star' title='WOW!!!' data-value='5'><i class='fa fa-star fa-fw'></i></li>
            </ul>
            <span class="validation text-danger hidden">CHOOSE A RATING!</span>
        </div>

        <div class="form-group controls">
            <label class="control-label col-md-2" for="Title">Title:</label>
            <div class="col-md-12">                
                <input name="Title" class="form-control" />
                <span class="validation text-danger hidden">You must enter a title.</span>
            </div>
        </div>

        <div class="form-group controls">
            <label class="control-label col-md-2" for="Content">Review:</label>
            <div class="col-md-12">
                <textarea name="Content" rows="6" class="form-control"></textarea>
                <span class="validation text-danger hidden">You must enter text.</span>
            </div>
        </div>

        <div class="form-group controls">
            <div class="col-md-12">
                <div class="alert alert-success successMessage hidden">
                    <p class="text-center">Review submitted! Thank you!</p>
                </div>
                <div class="alert alert-warning errorMessage hidden">
                    <p class="text-center errorMessageText"></p>
                </div>                
            </div>
        </div>

        <br />

        <div class="form-group controls">
            <div class="col-md-12">
                <button type="button" class="btn btn-sm btn-danger col-md-3 col-md-offset-1 createReview_close">Close</button>
                <button type="submit" class="btn btn-sm btn-success col-md-3 col-md-offset-4 createReview_submit">Submit</button>
            </div>
        </div>
        }
        else
        {
            <div class="text-warning alert">
                <p><i class="glyphicon glyphicon-warning-sign"></i>You must login before submitting a review!</p>
            </div>
            <div class="col-md-12">
                <button type="button" class="btn btn-sm btn-danger center-block createReview_close">Close</button>
            </div>            
        }
    }
    
</div>

<script type="text/javascript">
    $(document).on("click", ".reviewFilter", function(){
        if (@stats.Rating == 0) return false;
        $(".reviewFilter").removeClass("active");
        $(this).addClass("active");
        
        var rating = $(this).data("value");
        
        $.ajax({
            url: '@Url.Action("ListOfReviewsByTrail", "Trails")',
            type: "get",
            data: {
                id: @ViewBag.TrailID,
                rating: rating
            },
            success: function(result) {
                $("#reviewList").html(result);
            }
        });
    });

    $(document).on("click", ".reviewItem", function(){
        $(".reviewItem").removeClass("active");
        $(this).addClass("active");

        var title = $(this).data('title');
        var content = $(this).data('content');
        var user = $(this).data('user');
        var date = $(this).data('date');
        var rating = $(this).data('rating');

        $("#selectedReviewTitle").text(title)
        $("#selectedReviewContent").text(content);        
        $("#selectedReviewUser").text("By: " + user);
        $("#selectedReviewDate").text("Submitted: " + date);        
    });


    $(document).on('click', 'button[type="submit"]', function(e){
        validateForm();
        return false;
    });
    $(document).on('click', '.star', function(e){
        $(".rating-stars").children(".validation").addClass("hidden");
        return false;
    });
    $(document).on('change', 'input[name="Title"], textarea[name="Content"]', function(e){
        $(e.target).siblings(".validation:not(.hidden)").addClass("hidden");
        return false;
    });

    function validateForm(){
        var rating = $('.star.selected').length;
        var title = $("input[name='Title']").val();
        var content = $("textarea[name='Content']").val();

        var valid = true;

        //validation
        if (rating == 0){
            $(".rating-stars").children(".validation").removeClass("hidden");
            valid = false;
        } 
        if (title.trim() == "") {
            $("input[name='Title']").siblings(".validation").removeClass("hidden");
            valid = false;
        } 
        if (content.trim() == ""){
            $("textarea[name='Content']").siblings(".validation").removeClass("hidden");
            valid = false;
        } 
        
        //form submissions
        if (valid) {
            $("form.reviewForm input[name='Rating']").val(rating);
            $("form.reviewForm input[name='TrailID']").val(@ViewBag.TrailID);

            var formData = $("form.reviewForm").serialize();
            $.ajax({
                url:'@Url.Action("UserCreateReview", "Trails")',
                type:'POST',
                enctype:'multipart/form-data',
                dataType:'json',
                data: formData,
                success:function(response){
                    $(".successMessage").toggleClass("hidden");
                    $(".createReview_submit").toggleClass("hidden");
                    setTimeout(function(){
                        $(".successMessage").toggleClass("hidden");
                        ResetAndClose();
                    }, 2000);                    
                },
                error:function(response){
                    $(".errorMessageText").text("Something went wrong, try reloading the page and try again.");
                    $(".errorMessage").toggleClass("hidden");
                    $(".createReview_submit").toggleClass("hidden");
                    setTimeout(function(){
                        $(".errorMessage").toggleClass("hidden");
                        ResetAndClose();
                    }, 5000);
                }
            });
        }
    }

    function ResetAndClose(){
        //reset & close
        $("input[name='Title']").val('');
        $("textarea[name='Content']").val('');
        $(".star").removeClass("selected");
        $('#createReview').popup('hide');
        $('.createReview_submit').removeClass('hidden');
        location.reload();
    }
</script>



<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyCuLNIGdQlLxGfis0U_TxXgjdaluJa8dxA&sensor=false"></script>
<script type="text/javascript">

    function initialize() {
        var lat = @Html.Raw(Json.Encode(Model.Latitude));
        var lon = @Html.Raw(Json.Encode(Model.Longitude));
        var name = '@Html.Raw(Json.Encode(Model.Name))';

        var mapOptions = {
            center: new google.maps.LatLng(lat, lon),
            zoom: 10,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
        var latlng = new google.maps.LatLng(lat, lon);
        var marker = new google.maps.Marker({
            position: latlng,
            map: map,
            title: name
        });
    }

    window.onload = function(){
        initialize();
    }
</script>

NMCT/Views/Trails/Edit.cshtml
@model NMCT.Models.Trail

@{
    ViewBag.Title = "Edit Trail";
}

<h2>Trail Management | Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Trail Information</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TrailID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.County, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.County, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.County, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @row = 5} )
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Trails", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NMCT/Views/Trails/ListOfReviewsByTrail.cshtml
@model IEnumerable<NMCT.Models.Review>

<div class="list-group list-group-hover">
    <a class="list-group-item list-group-item-heading no-pointer"><span><strong>Review Title</strong></span></a>
    @foreach (NMCT.Models.Review review in Model)
    {
        <a class="list-group-item reviewItem" 
                data-title="@review.Title" 
                data-content="@review.Content" 
                data-date="@review.DateCreated.ToShortDateString()" 
                data-user="@review.UserName" 
                data-rating="@review.Rating">
            @Html.DisplayFor(modelItem => review.Title)
            <span class="badge">@Html.DisplayFor(modelItem => review.Rating)
                <i class='fa fa-star fa-fw'></i>
            </span>
        </a>
    }
</div>